version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      TZ: "Asia/Almaty"
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -p ${POSTGRES_PORT} -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
  
  volumes:
  postgres-data:
